# Generated by Django 5.1.7 on 2025-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the turbine', max_length=100, unique=True)),
                ('company_name', models.CharField(help_text='The company name', max_length=50)),
                ('rotor_diameter', models.FloatField(help_text='The rotor diameter in meters')),
                ('efficiency', models.FloatField(help_text='Power coefficient (Cp), typically between 0.3 and 0.5')),
                ('nominal_power', models.FloatField(help_text='Nominal power output in W (Watts)')),
                ('startup_speed', models.FloatField(help_text='Minimum wind speed required for the turbine to start (m/s)')),
            ],
        ),
    ]
