# Generated by Django 5.1.7 on 2025-03-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turbine',
        ),
    ]
