# Generated by Django 5.2b1 on 2025-05-21 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_winddataapi_winddatacsv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindData',
        ),
        migrations.AddField(
            model_name='turbine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turbines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winddatacsv',
            name='csv_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
