# Generated by Django 5.2b1 on 2025-05-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_delete_winddata_turbine_user_winddatacsv_csv_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbine',
            name='name',
            field=models.CharField(db_index=True, help_text='The name of the turbine', max_length=100),
        ),
    ]
