# Generated by Django 5.2b1 on 2025-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0007_alter_turbine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="winddatacsv",
            name="source",
            field=models.CharField(default="csv", max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="winddatacsv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
