# Generated by Django 5.2b1 on 2025-06-05 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebApp", "0008_winddatacsv_source_alter_winddatacsv_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winddatacsv",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
